# Data path. adjust them!
common:
    # image_file: "/home/chris/testing/lidar_cam_calib/scene_based/livox_camera_calib/src/livox_camera_calib/data/single_scene_calibration/3.png"
    # pcd_file: "/home/chris/testing/lidar_cam_calib/scene_based/livox_camera_calib/src/livox_camera_calib/data/single_scene_calibration/3.pcd"
    image_file: "/home/chris/testing/lidar_cam_calib/scene_based/livox_camera_calib/src/livox_camera_calib/data/scene_based_mlcc/bridge/low_ex.png"
    pcd_file: "/home/chris/testing/lidar_cam_calib/scene_based/livox_camera_calib/src/livox_camera_calib/data/scene_based_mlcc/bridge/merged_cloud_8.pcd"
    result_file: "/home/chris/testing/lidar_cam_calib/scene_based/livox_camera_calib/src/livox_camera_calib/output/extrinsics.txt"

# Camera Parameters. Adjust them!
camera:
    # camera_matrix: [1364.45, 0.0,      958.327,
    #             0.0,     1366.46,  535.074,
    #             0.0,     0.0,      1.0     ]
    # dist_coeffs: [0.0958277, -0.198233, -0.000147133, -0.000430056, 0.000000]
    camera_matrix: [1048.281 , 0.0,       1047.119,
                    0.0,       1048.161,  786.391,
                    0.0,       0.0,       1.0      ]
    dist_coeffs: [-0.178134, 0.051380, -0.000070, -0.000466, 0.000000]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/chris/testing/lidar_cam_calib/scene_based/livox_camera_calib/src/livox_camera_calib/config/config_outdoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
