%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
ImageTopic: "/camera/color/image_raw"

# Lidar Data type(custom msg or pointcloud2)
Data.custom_msg: 0
# Initial extrinsic (usually provided by hand measurement or cad design)

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0,   -1.0,   0.0,    0.07,
         0.0,   0.0,   -1.0,    0.04,
         1.0,   0.0,    0.0,    0.06,
         0.0,   0.0,    0.0,    1.0]
  # data: [-0.0871027, -0.9955878, -0.0348995, 0.1,
  #       0.0317269, -0.0377872, -0.9987820, -0.1,
  #       0.9956940,  0.0858893,  0.0348782, 0.1,
  #       0.0      ,  0.0      ,  0.0,    1.0]
  # data: [0.0523360, -0.9986295, -0.0000000, 0.1,
  #        0.0000000, -0.0000000, -1.0000000, -0.1,
  #        0.9986295,  0.0523360,  0.0000000, 0.1,
  #        0.0      ,  0.0      ,  0.0,    1.0]
  # data: [ 0.0871557,   -0.9961947,   0.0,    0.5,
  #       0.0,             0.0,     -0.9,    -0.3,
  #       0.9961947,   0.0871557,    0.0,    1.0,
  #       0.0,   0.0,    0.0,    1.0] # -5 degrees offset
  # data: [0.0,   -1.0,   0.0,    0.0,
  #        0.0,  0.0,  -1.0,    0.0,
  #        1.0,   0.0,    0.0,    0.0,
  #        0.0,   0.0,    0.0,    1.0]
# Params for Canny Edge Extraction

Canny.gray_threshold: 20
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 1.0
Voxel.down_sample_size: 0.02
Plane.min_points_size: 60
Plane.normal_theta_min: 30
Plane.normal_theta_max: 150
Plane.max_size: 5
Ransac.dis_threshold: 0.015
Ransac.iter_num: 200
Edge.min_dis_threshold: 0.03
Edge.max_dis_threshold: 0.06

# Params for color point clouds
Color.dense: 1
Color.intensity_threshold: 10